// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwevkxoiyhncmdqccptp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZXZreG9peWhuY21kcWNjcHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTAyMDMsImV4cCI6MjA2MDAyNjIwM30.i3-o3MBVhJ4AVn3UPBD9WsNXVwHNuSGip2mhbQxEmME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);